import { NetworkOptions } from "@/components/models/network";

export const TEST_NETWORKS: NetworkOptions[] = [
  {
    active: true,
    selected: true,
    network: "goerli",
    symbol: "ETH",
    title: "Goerli Testnet",
    description: "",
    icon: "/networks/eth.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "bscTestnet",
    symbol: "BSC",
    title: "BSC Testnet",
    description: "",
    icon: "/networks/bnb.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "polygonMumbai",
    symbol: "MATIC",
    title: "Polygon Mumbai",
    description: "",
    icon: "/networks/matic.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "avalancheFuji",
    symbol: "AVAX",
    title: "Avalanche Fuji",
    description: "",
    icon: "/networks/avax.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "fantomTestnet",
    symbol: "FTM",
    title: "Fantom Testnet",
    description: "",
    icon: "/networks/ftm.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "iotexTestnet",
    symbol: "IOTX",
    title: "IoTeX Testnet",
    description: "",
    icon: "/networks/iotex.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "optimismGoerli",
    symbol: "OP",
    title: "Optimism Goerli",
    description: "",
    icon: "/networks/optimism.svg",
    isTest: true,
  },
  {
    active: true,
    selected: false,
    network: "celoAlfajores",
    symbol: "CELO",
    title: "Celo Alfajores",
    description: "",
    icon: "/networks/celo.svg",
    isTest: true,
  },
];

export const NETWORKS: NetworkOptions[] = [
  {
    active: true,
    selected: true,
    network: "mainnet",
    symbol: "ETH",
    title: "Ethereum Mainnet",
    description: "",
    icon: "/networks/eth.svg",
  },
  {
    active: true,
    selected: false,
    network: "bsc",
    symbol: "BSC",
    title: "Binance Smart Chain",
    description: "",
    icon: "/networks/bnb.svg",
  },
  {
    active: true,
    selected: false,
    network: "polygon",
    symbol: "MATIC",
    title: "Polygon",
    description: "",
    icon: "/networks/matic.svg",
  },
  {
    active: true,
    selected: false,
    network: "avalanche",
    symbol: "AVAX",
    title: "Avalanche",
    description: "",
    icon: "/networks/avax.svg",
  },
  {
    active: true,
    selected: false,
    network: "fantom",
    symbol: "FTM",
    title: "Fantom",
    description: "",
    icon: "/networks/ftm.svg",
  },
  {
    active: true,
    selected: false,
    network: "iotex",
    symbol: "IOTX",
    title: "IoTeX",
    description: "",
    icon: "/networks/iotex.svg",
  },
  {
    active: true,
    selected: false,
    network: "optimism",
    symbol: "OP",
    title: "Optimism",
    description: "",
    icon: "/networks/optimism.svg",
  },
  {
    active: true,
    selected: false,
    network: "celo",
    symbol: "CELO",
    title: "Celo",
    description: "",
    icon: "/networks/celo.svg",
  },
];
